# Generated by Django 5.0.1 on 2024-01-29 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apostilas', '0002_viewapostila'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewapostila',
            name='avaliacao',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
