# Generated by Django 5.0.1 on 2024-01-31 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apostilas', '0003_viewapostila_avaliacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewapostila',
            name='avaliacao',
        ),
        migrations.AddField(
            model_name='apostila',
            name='avaliacao',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
