# Generated by Django 5.0.1 on 2024-01-24 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0003_flashcarddesafio_desafio'),
    ]

    operations = [
        migrations.AddField(
            model_name='desafio',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
